# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'islem.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(629, 551)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(70, 50, 491, 451))
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(80, 60, 321, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fiyat_label = QtWidgets.QLabel(self.layoutWidget)
        self.fiyat_label.setObjectName("fiyat_label")
        self.gridLayout.addWidget(self.fiyat_label, 1, 0, 1, 1)
        self.fiyat_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.fiyat_lineEdit.setObjectName("fiyat_lineEdit")
        self.gridLayout.addWidget(self.fiyat_lineEdit, 1, 1, 1, 1)
        self.satis_sayisi_label = QtWidgets.QLabel(self.layoutWidget)
        self.satis_sayisi_label.setObjectName("satis_sayisi_label")
        self.gridLayout.addWidget(self.satis_sayisi_label, 3, 0, 1, 1)
        self.stok_sayisi_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.stok_sayisi_lineEdit.setObjectName("stok_sayisi_lineEdit")
        self.gridLayout.addWidget(self.stok_sayisi_lineEdit, 2, 1, 1, 1)
        self.enst_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.enst_lineEdit.setObjectName("enst_lineEdit")
        self.gridLayout.addWidget(self.enst_lineEdit, 0, 1, 1, 1)
        self.satis_sayisi_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.satis_sayisi_lineEdit.setObjectName("satis_sayisi_lineEdit")
        self.gridLayout.addWidget(self.satis_sayisi_lineEdit, 3, 1, 1, 1)
        self.stok_sayisi_label = QtWidgets.QLabel(self.layoutWidget)
        self.stok_sayisi_label.setObjectName("stok_sayisi_label")
        self.gridLayout.addWidget(self.stok_sayisi_label, 2, 0, 1, 1)
        self.enst_adi_label = QtWidgets.QLabel(self.layoutWidget)
        self.enst_adi_label.setObjectName("enst_adi_label")
        self.gridLayout.addWidget(self.enst_adi_label, 0, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 330, 271, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.guncelle_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.guncelle_pushButton.setObjectName("guncelle_pushButton")
        self.gridLayout_2.addWidget(self.guncelle_pushButton, 0, 0, 1, 1)
        self.sil_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.sil_pushButton.setObjectName("sil_pushButton")
        self.gridLayout_2.addWidget(self.sil_pushButton, 0, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.widget)
        self.widget1.setGeometry(QtCore.QRect(80, 30, 101, 21))
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.widget1)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.id_label = QtWidgets.QLabel(self.widget1)
        self.id_label.setText("")
        self.id_label.setObjectName("id_label")
        self.gridLayout_3.addWidget(self.id_label, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İŞLEM SAYFASI"))
        self.fiyat_label.setText(_translate("Form", "FİYAT"))
        self.satis_sayisi_label.setText(_translate("Form", "SATIŞ SAYISI"))
        self.stok_sayisi_label.setText(_translate("Form", "STOK SAYISI"))
        self.enst_adi_label.setText(_translate("Form", "ENSTRÜMAN ADI"))
        self.guncelle_pushButton.setText(_translate("Form", "Güncelle"))
        self.sil_pushButton.setText(_translate("Form", "SİL"))
        self.label.setText(_translate("Form", "   ID |"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
