# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yeni_kayit2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(561, 390)
        self.bilgi_widget = QtWidgets.QWidget(Form)
        self.bilgi_widget.setGeometry(QtCore.QRect(70, 100, 421, 66))
        self.bilgi_widget.setObjectName("bilgi_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.bilgi_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fiyat_label = QtWidgets.QLabel(self.bilgi_widget)
        self.fiyat_label.setObjectName("fiyat_label")
        self.gridLayout_2.addWidget(self.fiyat_label, 1, 0, 1, 1)
        self.fiyat_lineEdit = QtWidgets.QLineEdit(self.bilgi_widget)
        self.fiyat_lineEdit.setObjectName("fiyat_lineEdit")
        self.gridLayout_2.addWidget(self.fiyat_lineEdit, 1, 1, 1, 1)
        self.enstruman_label = QtWidgets.QLabel(self.bilgi_widget)
        self.enstruman_label.setObjectName("enstruman_label")
        self.gridLayout_2.addWidget(self.enstruman_label, 0, 0, 1, 1)
        self.enstruman_lineEdit = QtWidgets.QLineEdit(self.bilgi_widget)
        self.enstruman_lineEdit.setObjectName("enstruman_lineEdit")
        self.gridLayout_2.addWidget(self.enstruman_lineEdit, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setHorizontalSpacing(10)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stok_label = QtWidgets.QLabel(self.bilgi_widget)
        self.stok_label.setObjectName("stok_label")
        self.gridLayout_3.addWidget(self.stok_label, 0, 0, 1, 1)
        self.stok_saysi_lineEdit = QtWidgets.QLineEdit(self.bilgi_widget)
        self.stok_saysi_lineEdit.setObjectName("stok_saysi_lineEdit")
        self.gridLayout_3.addWidget(self.stok_saysi_lineEdit, 0, 1, 1, 1)
        self.satis_label = QtWidgets.QLabel(self.bilgi_widget)
        self.satis_label.setObjectName("satis_label")
        self.gridLayout_3.addWidget(self.satis_label, 1, 0, 1, 1)
        self.satis_sayisi_lineEdit = QtWidgets.QLineEdit(self.bilgi_widget)
        self.satis_sayisi_lineEdit.setObjectName("satis_sayisi_lineEdit")
        self.gridLayout_3.addWidget(self.satis_sayisi_lineEdit, 1, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(180, 210, 160, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.kaydet_button_horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.kaydet_button_horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.kaydet_button_horizontalLayout.setObjectName("kaydet_button_horizontalLayout")
        self.kaydet_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.kaydet_pushButton.setObjectName("kaydet_pushButton")
        self.kaydet_button_horizontalLayout.addWidget(self.kaydet_pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "YENİ KAYIT"))
        self.fiyat_label.setText(_translate("Form", "Fiyat"))
        self.enstruman_label.setText(_translate("Form", "Enstrüman "))
        self.stok_label.setText(_translate("Form", "Stok Sayısı"))
        self.satis_label.setText(_translate("Form", "Satış Sayısı"))
        self.kaydet_pushButton.setText(_translate("Form", "KAYDET"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
